### ISSUE TITLE
Title parameter for download doesn't work solidly

### ISSUE THREAD

**Issue by Baloobear** [heimrichhannot/contao-inserttagcollection-bundle#3] opened 2021-08-05 13:47 UTC
**Context**
Contao version: 4.5.11
Bundle version: current (1.1.3)
PHP version: 7.4

**Description**
It seems that the `{{download}}` inserttag sometimes doesn't concern of the second parameter for a custom label. It's using the title set in the filemanagement (if set) or the filename as default.

I used the scheme `{{download::UUID::my custom label}}` for multiple PDF files (of different sizes) in different text content elements (within one article). Sometimes the title parameter is used but mostly not.

Is there a chance to debug this somehow? I presume that the issue may be related to my system but I'm not sure.

Thanks in advance.

Kind regards,
Dennis

**Comment by koertho** [comment] 2021-08-09 06:46
@Baloobear Hi, thanks for reporting. 4.5.11 seems to be a long unsupported version. Can you reproduce this issue in an LTS or current release?

**Comment by Baloobear** [comment] 2021-08-11 07:36
Hello @koertho,

sorry, my fault. I had a typo.
The used Contao version is 4.11.5 (not 4.5.11 🤦‍♂️).

Kind regards,
Dennis

EDIT: I added my composer.* files if needed.

[composer.zip](https://github.com/heimrichhannot/contao-inserttagcollection-bundle/files/6966646/composer.zip)

**Comment by Baloobear** [comment] 2021-08-31 22:55
Is there any update regarding this issue?

**Comment by Defcon0** [comment] 2021-09-01 11:29
I just checked in latest contao 4.9 and 4.11, works without problems.

I tried `{{download::c4397bd9-0b05-11ec-968c-001e678385c6::my custom label}}`.

**Closed as completed by Defcon0** 2021-09-01 11:29 UTC

**Comment by Baloobear** [comment] 2021-09-07 12:04
Hi,

have you tried it with multiple but different download InsertTags, too?

Just wat to be sure. If yes I'll have to do a deep-dive on my own what may interrupt the correct function of this InsertTag. I assume you tested it with a fresh CMS installations, right?

Kind regards,
Dennis

**Comment by Defcon0** [comment] 2021-09-07 13:29
Not a fresh instance due to time constraints, but it should make no difference. Also tested with different files, worked.
